services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dhv'
      - 'POSTGRES_PASSWORD=DHV1234!'
      - 'POSTGRES_USER=dhv_core'
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'