ALTER TABLE addresses
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE parcels
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE recipients
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
