spring:
  application:
    name: dhv

  datasource:
    url: jdbc:postgresql://localhost:5432/parcel_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true

  docker:
    compose:
      enabled: false

logging:
  level:
    org.flywaydb: DEBUG
