spring:
  application:
    name: dhv

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:parcel_db} # should be changed to default docker db (dhv)
    username: ${DB_USER:postgres} # should be changed to default docker user (dhv_core)
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true

  mail:
    host: localhost
    port: 1025
    username: no-reply@dhv.local
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  docker:
    compose:
      enabled: false

logging:
  level:
    org.flywaydb: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.tcs.dhv.controller
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 15m

auth:
  refresh-token-ttl: 24h
  reset-token-ttl: 15m

email-verification:
  required: true

app:
  base-url: http://localhost:8080

dhv:
  client-url: http://localhost:5173
api:
  key:
    header:
      name: X-API-Key
